name: flutter_survey_js
description: Parse and display survey js
version: 0.0.2-dev.1
homepage: https://github.com/Goxiaoy/flutter_survey_js

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  scrollable_positioned_list: ^0.3.5
  im_stepper: ^1.0.1+1
  flutter_widget_from_html_core: ^0.10.0
  # https://github.com/Innim/flutter_multiple_localization/pull/12
  multiple_localization:
    git:
      url: https://github.com/goxiaoy/flutter_multiple_localization.git
      ref: master

  reactive_forms: ^14.3.0
  reactive_date_time_picker: ^0.6.1
  reactive_date_range_picker: ^0.6.0
  reactive_segmented_control: ^0.6.0
  reactive_advanced_switch: ^0.6.1
  reactive_image_picker: ^2.0.0
  implicitly_animated_reorderable_list_2: ^0.5.0
  flutter_colorpicker: ^1.0.3
  signature: ^4.1.1
  logging: ^1.0.1
  platform: ^3.1.0
  file: ^6.1.4
  group_button: ^5.2.2
  flutter_survey_js_model: ^0.0.2-dev.1
  built_value: ">=8.4.0 <9.0.0"
  built_collection: ">=5.1.1 <6.0.0"
  intl: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  melos: ^3.0.1

dependency_overrides:
  intl: 0.18.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  uses-material-design: true
flutter_intl:
  enabled: true
