name: Pages
on:
  workflow_run:
    workflows: ["Analyze & Test"]
    types: [completed]
    branches: [main]

  workflow_dispatch:
jobs:
  publish:
    name: Publish Github Pages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          channel: "stable"
      - name: Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          dart pub global activate melos 3.1.1
      - name: Bootstrap melos
        run: melos bs --verbose
      - run: |
          cd example
          flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
