name: Analyze & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          dart pub global activate melos 3.0.1
      - name: Bootstrap melos
        run: melos bs
      - name: Run tests
        run: melos run test
      - run: |
          cd example
          flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true

#      - name: "Run Analyze"
#        run: melos run analyze

#      - name: "Pub Check"
#        run: |
#          melos exec -c 1 --no-private --ignore="*example*"  -- \
#            flutter pub publish --dry-run
